[ci skip] Pushing deployment files for namespace and service accounts
Signed-off-by: nikhilayadav <nikhila.golla@accenture.com>

diff --git a/platforms/hyperledger-besu/charts/orion_key_mgmt/templates/job.yaml b/platforms/hyperledger-besu/charts/orion_key_mgmt/templates/job.yaml
--- a/platforms/hyperledger-besu/charts/orion_key_mgmt/templates/job.yaml
+++ b/platforms/hyperledger-besu/charts/orion_key_mgmt/templates/job.yaml
@@ -1,3 +1,9 @@
+##############################################################################################
+#  Copyright Accenture. All Rights Reserved.
+#
+#  SPDX-License-Identifier: Apache-2.0
+##############################################################################################
+
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -90,8 +96,27 @@ spec:
               LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
                 -H "Content-Type: application/json" \
                 -X POST \
-                -d '{"data": {"key":"'"$nodekey_base64"'","key_pub":"'"$(cat nodeKey.pub)"'","password":"'"$(cat password_file)"'"}}' \
+                -d '{"data": {"privateKey":"'"$nodekey_base64"'","publicKey":"'"$(cat nodeKey.pub)"'","password":"'"$(cat password_file)"'"}}' \
                 ${VAULT_ADDR}/v1/${vault_secret_key} | \
                 jq -r 'if .errors then . else .auth.client_token end')
               
               validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+
+              # get privateKey from vault
+              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${vault_secret_key} | jq -r 'if .errors then . else . end')
+              privateKey=$(echo ${VAULT_RESPONSE} | jq -r '.data.data["privateKey"]' 2>&1)
+              # get publicKey from vault
+              publicKey=$(echo ${VAULT_RESPONSE} | jq -r '.data.data["publicKey"]' 2>&1)
+
+              if [ "$privateKey" == "null" ] || [ "$publicKey" == "null" ] || [ "$privateKey" == "parse error"* ]|| [ ""$publicKey"" == "parse error"* ]
+              then
+                echo "certificates write or read fail"
+                sleep {{ $.Values.healthcheck.readinessthreshold  }}
+                if [ "$COUNTER" -ge {{ $.Values.vault.retries }} ]
+                then
+                  echo "Retry attempted $COUNTER times, certificates have not been saved"
+                  exit 1
+                fi
+                COUNTER=`expr "$COUNTER" + 1`
+              fi
+              
